### ISSUE TITLE
Use GPUs when running the workflow

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#13]
Some steps in the workflow may benefit from using a GPU.
Update the workflow to properly request GPU resources.

**Comment by johnbradley** [comment]
# Snakefile
Snakemake has [step resource options support for specifying the gpu requirements]( https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=gpu#gpu-resources).
For example we might add the following two lines to a step in the Snakefile:
```
    resources:
        gpu=1
```

# sbatch
Snakemake will need to pass the `resources.gpu` value value to the `sbatch` command.
The OSC cluster has [documentation on using their GPUs](https://www.osc.edu/resources/technical_support/supercomputers/gpu_computing).
For example we might need to set `--gpus-per-node=1` for sbatch.
If PR #12 is accepted we would need to add something like `--gpus-per-node={resources.gpu}` here:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/a90418ce81c91c07bc0f9829a2e1383dce6df8d8/slurm/config.yaml#L3-L7

# singularity
We currently use singularity to provide our software environments.  Singularity has documentation on [gpu enabled container requirements](https://sylabs.io/guides/3.8/user-guide/gpu.html?highlight=gpu#nvidia-gpus-cuda).
From the command line perspective it looks like we may need to include `--nv` when running singularity.
We could try adding this flag here:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/9e932d61be4ef83bfb92b94605c49fb34374d992/SLURM_Snake#L51

**Comment by thibaulttabarin** [comment]
Thanks John, it works well.
