### ISSUE TITLE
Improve documentation/cleanup for SLURM*, snakefile* and Dockerfile

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#20]
Looking at the repo I'm kinda confused about which scripts should be run and when.
Please document when and how a user should run them and remove any that are no longer needed.

There three SLURM_Snake* scripts that will run snakemake in an sbatch job: 
- [SLURM_Snake](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/SLURM_Snake)
- [SLURM_Snake_v2](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/SLURM_Snake_v2)
- [SLURM_Snake_v3](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/SLURM_Snake_v3)

There are 4 Snakefile* scripts that make up various Snakemake pipelines: 
- [Snakefile](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/Snakefile)
- [Snakefile_merge](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/Snakefile_merge)
- [Snakefile_v2](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/Snakefile_v2)
- [Snakefile_morphology_v3](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/Snakefile_morphology_v3)

One of the powerful features of Snakemake is you can specify the target you wish to create. See target under https://snakemake.readthedocs.io/en/stable/executing/cli.html#EXECUTION. For example you could allow user to specify a morphology target for example if they want to do just that subset of the processing.

There is also now a Docker container packaged with this repo: `ghcr.io/hdr-bgnn/bgnn_snakemake:0.0.5`.
Just based on the name I would assume that this is the entire workflow, but I think it's just the morphology step.
Perhaps we could change the name to be bgnn_snakemake_morphology or move this logic into a separate repo for consistency with drexel metadata and bgnn-trait-segmentation.

Thanks.

**Comment by thibaulttabarin** [comment]
clo
