### ISSUE TITLE
Fix NameError in rule Cropped_image

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#22]
The following error occurred when running the pipeline `Cropped_image` rule:
```
Traceback (most recent call last):
  File "/pipeline/Crop/Crop_image_main.py", line 20, in <module>
    ImageFile.LOAD_TRUNCATED_IMAGES = True
NameError: name 'ImageFile' is not defined
```
Within the container the python script looks like this:
```
from PIL import Image
import pandas as pd
from pathlib import Path
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
Current code:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/4626599f3d21ee3a148bdbd5a5592e598ce1624f/Scripts/Crop_image/Crop_image_main.py#L17-L20
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/4626599f3d21ee3a148bdbd5a5592e598ce1624f/Snakefile#L46-L53

It looks like the code has already been fixed, but a new version of the container needs to be built.

Thanks.

**Comment by thibaulttabarin** [comment]
Indeed, this error should have been fixed, I am surprised. I will fix it ASAP.

**Comment by thibaulttabarin** [comment]
I can't reproduce your error.
I tried:
singularity pull morpholo.sif docker://ghcr.io/hdr-bgnn/bgnn_snakemake/crop_morph:0.0.16
/fs/ess/PAS2136/BGNN/Minnows/Metadata/INHS_FISH_000742.json
/fs/ess/PAS2136/BGNN/Minnows/Metadata/INHS_FISH_000742.jpg

singularity exec morpholo.sif Crop_image_main.py INHS_FISH_000742.jpg INHS_FISH_000742.json image_crop_2.jpg
and it worked

**Comment by thibaulttabarin** [comment]
Nope, I can't reproduce the error.
I rerun the workflow on /fs/ess/PAS2136/BGNN/Minnows/Test_lab
using the SLURM_Snake and Snakefile as
SLURM_Snake /fs/ess/PAS2136/BGNN/Test_lab/ /fs/ess/PAS2136/BGNN/Test_lab/minnow.images.for.segmenting.10.csv 1
0
It worked great. In the past, I experienced some issue with the Snakemake when I was creating new container version somehow I had to clear the cache in .snakemake to make it works, never find out exactly what was the problem.

**Comment by johnbradley** [comment]
I was trying to use the 0.0.16 release: https://github.com/hdr-bgnn/BGNN_Snakemake/releases/tag/0.0.16.
Under the [0.0.16 tag](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/0.0.16/Snakefile) the code is still using the 0.0.15 image ?
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/1a90325e24a942bb818b46c96aa3745aeae4e2ec/Snakefile#L46-L52

**Comment by thibaulttabarin** [comment]
I remove morphology from this repo. 
Morphology-analysis has its own repo here https://github.com/hdr-bgnn/Morphology-analysis
Pull command (in general and in particular in Snakefile) has been changed to docker://ghcr.io/hdr-bgnn/morphology-analysis/morphology:0.0.1.
close #22
