### ISSUE TITLE
Fix error reading input CSV file

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#24]
I encountered the following error when trying to use https://github.com/hdr-bgnn/minnowTraits/blob/main/Files/Image_Metadata_v1_20211206_151152.csv as the input list:
```
ValueError: Length mismatch: Expected axis has 9 elements, new values have 2 elements
```
The error occurs on the following line:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/8e66f3717663cb6e2bc2c696d34c5247cd3783d3/Snakefile#L12

I think the problem is the the `original_file_name` column contains names with multiple periods such as `lecostomus_wuchereri_syntypeBMNH1863.3.27.15_195.0mm-S.jpg`.

Please
1. Fix the parsing to handle these type of filenames 
2. Document the expected format for the input CSV file

**Comment by johnbradley** [comment]
Here is the code in question:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/8e66f3717663cb6e2bc2c696d34c5247cd3783d3/Snakefile#L10-L15

The two places where we use this data are:
https://github.com/hdr-bgnn/BGNN_Snakemake/blob/8e66f3717663cb6e2bc2c696d34c5247cd3783d3/Snakefile#L17

and 

https://github.com/hdr-bgnn/BGNN_Snakemake/blob/8e66f3717663cb6e2bc2c696d34c5247cd3783d3/Snakefile#L31

I think this code is just trying to strip the extension from the `original_file_name` column and use that as the index for the dataframe and be able to lookup `path` for a simplified named. So we need to create a list of names based on original_file_name and be able to lookup a URL for each image name.

Would something like this work:
```
df = pd.read_csv(filename)
df['name'] = df['original_file_name'].apply(lambda x : os.path.splitext(x)[0])
df = df.set_index('name')
NAME_TO_URL = df['path']
```

**Comment by johnbradley** [comment]
I created a branch with a potential fix: https://github.com/hdr-bgnn/BGNN_Snakemake/commit/f0498d7dd87ca2ec3e5a13f4b2c3b1736323dd8b.

It might be nice to make the workflow more flexible about the input CSV format. For example letting the user supply the `name` and download `url` column names via config. That way users might not need to massage their input CSV files to meet the naming conventions here.

**Comment by thibaulttabarin** [comment]
It seems good but  I will have look at it in more detail. One thing to keep in mind this has been developed mainly for minnows project. Therefore I haven't trying other part of the dataset Image_Metadata_v1_20211206_151152.csv. Additionally keep in mind that other parts of the workflow may be specific to a particular museum dataset like Drexel_metadata part has only been trained for INHS and UWZM.

**Comment by johnbradley** [comment]
@thibaulttabarin I was thinking that it might be nice to make the workflow CSV input more configurable. Instead of hard coding the non intuitive(to me at least) `original_file_name` and `path` column names. Make them config options with defaults. If that sounds good I'll add that change to my branch and create a PR for you to review.

**Comment by meghalithic** [comment]
@johnbradley what about a template? I think that is more user-friendly for non computer scientists than asking them to create a config file. Perhaps something useful for Imageomics?

**Comment by meghalithic** [comment]
Also, if we use a template, perhaps this is something for the next version as it will take a lot of team buy-in.

**Comment by johnbradley** [comment]
> @johnbradley what about a template? I think that is more user-friendly for non computer scientists than asking them to create a config file. Perhaps something useful for Imageomics?

What do you mean by template? With snakemake the convention is to supply a config file in the repo at config/config.yaml with default values.

**Comment by thibaulttabarin** [comment]
I understand template, as this is the format for the input data (list), template is the example of the format. If someone uses this program they should comply with require format.

**Comment by meghalithic** [comment]
Exactly, so we'd need to discuss which headers are necessary and what they are called. E.g., image_file_name to read the list of images to download, and every file would need that column and column header.

**Comment by hlapp** [comment]
What you're describing is a data schema. I agree this would be useful and desirable to have. (Like many other things, data schemas can and do have versions, so there isn't really anything wrong with starting out with one schema and generalizing it later.)

BTW [LinkML](https://linkml.io/) seems to be getting quite a bit of attention lately for this purpose. Perhaps worth checking out.

**Comment by meghalithic** [comment]
I think we have two issues here:

1) making sure there are no csv reading errors for the images used in the minnows project (version 1.0.0).

2) the next step, which would increase usability, which would be either creating a schema or or using LinkML. This would be a broader conversation for the Imageomics group, perhaps something to discuss during the "workshop" portion of the meetings. The more generalizable version would be version 2.0.0.

**Comment by johnbradley** [comment]
One more option to consider for validating input files is [Snakemake built in support for json-schema](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#validation).

**Comment by thibaulttabarin** [comment]
Ok yes I like the idea about that [Snakemake built in support for json-schema](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#validation).
I think we could create a config file with the all moving part, I like to discuss about it during our meeting minnows workflow.
