### ISSUE TITLE
issues with debugging

### ISSUE THREAD

**Issue by meghalithic** [hdr-bgnn/BGNN_Snakemake#31]
how to handle when the OSC or other HPC updates, how to deal with de-bugging?

OSC has singularity program, which may not match the workflow program

maybe need to make container for snakemake with correct singularity program

**Comment by meghalithic** [comment]
@johnbradley, here is what @thibaulttabarin and I did today to debug:

**Issue**: I was not able to run `Snake_download` or `Snake_metadata` (on [Minnow_Traits, Workflow_analysis branch in Step_by_step in Workflows_minnows folder](https://github.com/hdr-bgnn/Minnow_Traits/tree/Workflows_analysis/Workflows_minnows/Step_by_step))
- I had already pulled the most recent changes and was on the correct branch
- I tried running this command on both the base note and in the snakemake environment

**Error**: the slurm.out file said that I did not have permission and needed to specify the account. At first we thought it was permission to PAS2136, which I did have, and which is specified in the SLURM files.

**Solution 1**: update packages/software
- We updated Snakemake
- OSC has a default Snakemake that is not the same version as in the container
- To update Snakemake, we needed to update python
- I specifically needed to update it in my own repository (I think, may need Thibault to confirm)

_Still got the same error..._

**Solution 2**: debug using sinteractive 

_Still got the same error..._

**Solution 3**: Test if can use sbatch in general
- Copied OSC-Batch-Training to my home directory
- ran openmp.sh (which creates hello_results)
- ran fine

**Solution 5**: Test locally
- copied subset of fish images (minnow.images.for.segmenting.10.csv) in a local folder, Test_lab
- Ran: 
```
snakemake --cores 1 --snakefile Snake_download --config list=/users/PAS2136/balkm/T
est_Lab/minnow.images.for.segmenting.10.csv
```
- it worked!
- duplicated SLURM_Snake_generic and renamed it SLURM_Snake_Test
    - we changed it so that it would run on only one core.

_...same error..._

**Solution 5**: I needed access to the [metadata container](https://could.sylabs.io/library/thibaulttabarin/bgnn/gen_metadata). This doesn't make sense because the container is already set up and called in the workflow.
- needed to ask for access to an apptainer without a login
   - [instructions](https://apptainer.org/docs/user/1.0/endpoint.html#restoring-pre-apptainer-library-behavior)
   - **Note**: I would not have know how to debug of know that apptainer is for singularities/containers
- re-ran 
`sbatch SLURM_Snake_test Snake_metadata 5`
- took too long and _failed_
    - we wanted to re-run it using `SLURM_Snake_generic Snake_metadata`

For now, we're going to have Thibault finish all the fine-tuning, then re-approach debugging.

**Comment by thibaulttabarin** [comment]
by the way, I just rerun the whole dataset step_by_step for [burress](https://github.com/hdr-bgnn/Minnow_Traits/blob/main/Files/burress.minnow.sp.filtered.from.imagequalitymetadata_25Jul2022.csv)
using the exact instruction I gave in the [readme](https://github.com/hdr-bgnn/Minnow_Traits/blob/Workflows_analysis/Workflows_minnows/Step_by_step/READ.md)
Everything worked fine.

**Comment by johnbradley** [comment]
@megbalk I would be glad to meet to figure out what is going wrong with running the pipeline. Were you running this code from this repo? It sounds like you were using code from https://github.com/hdr-bgnn/Minnow_Traits/tree/Workflows_analysis.

I think the apptainer issue will go away once we finish the migration to the github container registry.

**Comment by thibaulttabarin** [comment]
in term of diagnosis, I think based on what we have tried the problem comes form the --profile slurm/ (in SLURM_Snake_generic). I suspect that when the scheduler splits the task on multiple cores the account number is not carried on the individual task (I don't know if it make sense) and from memory the error was sbatch: error: ERROR: Job invalid: Must specify account for job.

**Comment by johnbradley** [comment]
Previously Slurm_Snake contained the following lines, but they have been subsequently removed for some unknown reason:
```
# Setup Snakemake/sbatch to use same account as this job
export SBATCH_ACCOUNT=$SLURM_JOB_ACCOUNT
```
https://github.com/johnbradley/BGNN_Snakemake/blob/a90418ce81c91c07bc0f9829a2e1383dce6df8d8/SLURM_Snake#L50-L51

The above change was part of https://github.com/hdr-bgnn/BGNN_Snakemake/pull/12.

I would suggest adding these lines back to your sbatch job script.

@thibaulttabarin Is `SLURM_Snake_generic` on a branch in this repo?

**Comment by thibaulttabarin** [comment]
yep, look like it should solve the issue, indeed I checked on my osc account and I do have env SBATCH_ACCOUNT assign to PAS2136, I probably set it up sometime ago and therefor I don't have the problem.

**Comment by thibaulttabarin** [comment]
no SLURM_Snake_generic is a branch on MinnowsTraits https://github.com/hdr-bgnn/Minnow_Traits/tree/Workflows_analysis/Workflows_minnows/Step_by_step

I will amend this part now
Thanks John you're the best. ;)

**Comment by thibaulttabarin** [comment]
@johnbradley  thanks john I am pretty this solved the problem. need to test with Meghan, but i remove my env variable BATCH_ACCOUNT from my account and I could reproduce Meghan error, then I made the change you suggested and it worked like a charm...

Quich question, how do I make the change on my branch but give you the credit... Or should I let you do the change...?

**Comment by johnbradley** [comment]
> Quich question, how do I make the change on my branch but give you the credit... Or should I let you do the change...?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Basically include a line in the commit message with `Co-authored-by: name <name@example.com>`.

**Comment by thibaulttabarin** [comment]
# Setup Snakemake/sbatch to use same account as this job
export SBATCH_ACCOUNT=$SLURM_JOB_ACCOUNT

commit 03b345e208ad1c7ae1e1a104ec2d3c5134c0c7ee fix the problem
https://github.com/hdr-bgnn/Minnow_Traits/commit/03b345e208ad1c7ae1e1a104ec2d3c5134c0c7ee
