### ISSUE TITLE
Consider renaming this repo

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#33]
This repo contains a single Snakemake workflow that runs an image segmentation pipeline. The first time I saw this repo name I assumed it was a BGNN customized version of the Snakemake software. I'm creating this issue to see if we can come up with a better name that more accurately represents the code here. Thanks.

**Comment by thibaulttabarin** [comment]
yes I agree, I came up with the name but that was not better than dice toss...

**Comment by meghalithic** [comment]
Is the purpose of this workflow _just_ for fish projects or for all the projects?
As I see it, each module can be swapped out. 
I think knowing the scope will help with figuring out an appropriate name.

**Comment by johnbradley** [comment]
> Is the purpose of this workflow just for fish projects or for all the projects?

I think this workflow is specific to fish.

----
@hlapp suggested renaming this repo to "BGNN_Core_Workflow". I think this is a better name. Thoughts @thibaulttabarin  @megbalk ?

**Comment by thibaulttabarin** [comment]
yes I like it! it is clear and explicit.

**Comment by thibaulttabarin** [comment]
> 

yes I like it! it is clear and explicit.

**Comment by meghalithic** [comment]
I like it too!

**Comment by johnbradley** [comment]
I renamed the repo to https://github.com/hdr-bgnn/BGNN_Core_Workflow.
Closing this issue.
