### ISSUE TITLE
Remove unrelated container build

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#44]
There is a GitHub action config file `Deploy_Crop_Morpho.yml` in this repo that tries to build a docker container. This docker build is failing. I'm not sure what the purpose of this container was. It isn't used by the Snakemake repo. Based on the name it seems like this config may have been accidentally added to this repo.
https://github.com/hdr-bgnn/BGNN_Core_Workflow/blob/19c414b2758273f9af66723e2a4349a6a6792b03/.github/workflows/Deploy_Crop_Morpho.yml#L1

**Comment by hlapp** [comment]
Remove? Also, there seem to be two packages (container images) from this repo on the GitHub registry. Should they be deleted? Or if not (hard to imagine though someone legitimately depends on them), we should probably add documentation to the README so people don't confused into trying to guess what they are for.

**Comment by johnbradley** [comment]
The two containers in this repo's Github registry `ghcr.io/hdr-bgnn/bgnn_snakemake:0.0.5` and `ghcr.io/hdr-bgnn/bgnn_snakemake/crop_morph:0.0.16` both contain `Crop_image_main.py` and `Morphology_main.py` scripts.
The `Crop_image_main.py` script is in another repo: https://github.com/hdr-bgnn/Crop_image/blob/main/Crop_image_main.py
The `Morphology_main.py` script is in another repo: https://github.com/hdr-bgnn/Morphology-analysis/blob/main/Scripts/Morphology_main.py

---

I think we should delete both these containers/packages. Users should use the containers built in the https://github.com/hdr-bgnn/Crop_image and https://github.com/hdr-bgnn/Morphology-analysis repos.

**Comment by johnbradley** [comment]
I removed the bogus github container building config in PR #47. 
I intended to remove the two bogus packages but I do not have permission to delete them:
https://github.com/hdr-bgnn/BGNN_Core_Workflow/pkgs/container/bgnn_snakemake%2Fcrop_morph
https://github.com/hdr-bgnn/BGNN_Core_Workflow/pkgs/container/bgnn_snakemake

Since these are within hdr-bgnn perhaps we need someone who is admin for that group?

**Comment by hlapp** [comment]
Indeed, I don't see the package settings link either which would then allow deletion of the package as one of the options. @cflorian1 do you?

**Comment by cflorian1** [comment]
@johnbradley and @hlapp yes, it does look like I can access the package settings link for both packages. Should I go ahead and delete?
