### ISSUE TITLE
Fix 404 error for metadata project in README

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#9]
I receive a 404 error when clicking the GitHub URL for the `Get metadata (container)` component in README.md:

https://github.com/hdr-bgnn/BGNN_Snakemake/blob/b55f3fac1f32fb91fb535c4257d02c0008b8160d/README.md?plain=1#L10

Perhaps the https://github.com/hdr-bgnn/drexel_metadata repo is still private.

**Comment by thibaulttabarin** [comment]
I think the problem is that the repo drexel_metadata is private.
I will try to change to "public" on that but I currently don't have admi rights. I will contact someone to make the change and get the admi right.

**Comment by thibaulttabarin** [comment]
I change the status for the https://github.com/hdr-bgnn/drexel_metadata repo to public.
Does it solve the problem?

**Comment by johnbradley** [comment]
Thanks @thibaulttabarin. I can now visit the URL in the README. Closing this issue.
